name: Deploy to Strato

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-strato:
    name: Deploy to Strato
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18  

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Clean remote directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        script: mkdir -p strixhaven && cd strixhaven && rm -rf *
    
    - name: Deploy site
      run: sshpass -p "${{ secrets.SFTP_PASSWORD }}" rsync -ae "ssh -o StrictHostKeyChecking=no -p 22" ./build/ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:./dnd